apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: multiple-sources
  namespace: argocd
spec: 
  destination: 
    namespace: multiple-sources
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: "https://kubernetes.github.io/ingress-nginx"
      targetRevision: 4.6.1
      helm:
        valueFiles:
          - $values/ingress-nginx/values.yaml
    - repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
      ref: values
      targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true