apiVersion: v1
kind: Secret
metadata:
  name: private-repo-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: argo
  url: https://argoproj.github.io/argo-helm
  password: g....
  username: m...
  tlsClientCertData: .....
  tlsClientCertKey: ....
